### PR TITLE
Update Pango builds for Visual Studio 2017

### PR DESCRIPTION
**Pull request by selgas**
https://github.com/TechSmith/CamtasiaWin/issues/9202

# Overview

This repo uses a series of Python scripts to download source code from various archives and automatically build a target project (in this case Pango). The version of GTK that we forked from doesn't really have full Visual Studio 2017 support, so I had to make some updates to get everything building. These include:

- [x] Update some download URLs in Python script to point to new locations
- [x] Create vc15 builds for freetype, gettext, and libffi projects
- [x] Fix gettext build to use "v141" toolset instead of "v150" toolset
- [x] Add a patch to GNU's memmove and memchr functions to fix build errors
- [x] Update autopkg version

# Build Server Notes

A big part of this PR is updating the build server to run the correct commands. Most notably, I had to manually set the location of Visual Studio 2017, so the new commands are:

**Win32 build**

```
Invoke-Expression "C:\Python36\python.exe %teamcity.build.checkoutDir%\build.py build --build-dir %teamcity.build.checkoutDir% -p x86 --vs-ver 15 --vs-install-path `"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise`" pango"
```

**x64 build**

```
Invoke-Expression "C:\Python36\python.exe %teamcity.build.checkoutDir%\build.py build --build-dir %teamcity.build.checkoutDir% -p x64 --vs-ver 15 --vs-install-path `"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise`" pango"
```

### CODE REVIEW

**Comment by ajorians** [comment]
Did we ever want to remove this file and add it to the .gitignore:
image

:smiley:

**Comment by ajorians** [comment]
Looks good to me! 👍 :smiley:

**Comment by BingTSC** [comment]
@selgas  so we didn't pull the the latest GTK code, but you did VS2017 upgrade manually?

so (1) how you get those vcxproj? it's intermediate things generated by build.py? 
     (2) how you generate .patch file?

Thank you.

**Comment by selgas** [comment]
@BingTSC Yes that's right. Some of the projects already had a vs15 build, but for the ones that didn't, I copied the vs14 folders and updated their projects manually to use v141 toolset. As for the patch file, I didn't really know how to use diff, so I made one manually. :smile:

**Pull request merged**
